# Dependabot configuration file

version: 2
updates:
  # Configuration pour Julia
  - package-ecosystem: "julia"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10

  # Configuration pour npm (Node.js)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10

  # Configuration pour GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10