name = "OrgSiteGenerator"
uuid = "5bbd6b1d-f185-427c-8e1a-4305d105cf5d"
authors = ["Anthea Liles"]
version = "0.1.0"

[deps]
Genie = "c27321d9-0574-5f3e-8a0d-6f7c8a4a7820"
Glob = { git = "https://github.com/vtjnash/Glob.jl" }
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
julia = "1.6"
Genie = "5.0.0 - 5.9.9"
Glob = "1.3.0 - 1.3.9"

[extras]
Documenter = "e30172f5-3f7a-5d0e-8460-6d60b8a78a4a"

[targets]
test = ["Test"]